# Generated by Django 5.2.8 on 2025-11-21 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'gasto'}, on_delete=django.db.models.deletion.CASCADE, to='finanzas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'ingreso'}, on_delete=django.db.models.deletion.CASCADE, to='finanzas.categoria')),
            ],
        ),
    ]
